### ISSUE TITLE
How to - non-expo react-native project

### ISSUE THREAD

**Issue by Zurdge** [chromaui/intro-storybook-react-native-template#3]
Recently spun up the "Storybook for React Native tutorial" which was really easy.
I began digging into how I could get Storybook for React-native working with a non-expo project but didn't find it as simple.

Are there any resources that show how I could get storybook working for a `npx react-native init MyApp --template react-native-template-typescript` project?

I will continue to dig into this later in the week as well.

**Comment by dannyhw** [comment]
expo is not required its just simpler for the tutorial.

you can add storybook to an existing project with: `npx sb@latest init --type react_native` 

or start a new project with the template: `npx react-native init MyApp --template react-native-template-storybook`

**Comment by Zurdge** [comment]
Thanks, `npx sb@latest init --type react_native` got me up and running 👍
